require "rake/clean"

["value_type", "gen_autogen_task"].each do |s|
  require "thrusting/rb/#{s}"
end

task :build => __FILE__ do |t|
  TYPES.zip(TUPLE_TYPES).each do |type, tuple_type|
    f = File.open("#{tuple_type}.h", "w")
    code =
"""
#pragma once
#include \"detail/n_typedef/#{tuple_type}.h\"
#include \"detail/make_n_typedef/#{tuple_type}.h\"
"""
    f.puts(code)
    f.close
  end
end

gen_autogen_task(["detail/n_typedef", "detail/make_n_typedef"])

CLOBBER.include(TUPLE_TYPES.map { |s| "#{s}.h" })
