require "rake/clean"

names = [
  "make_real_n",
  "make_tuple_n",
  "parallel_operator_a_a",
  "parallel_operator_a_a_a",
  "parallel_operator_a_b_a",
  "real_n_typedef",
  "tuple_n_operator",
  "tuple_operator",
  "tuple_n_typedef"
]

names.map { |x| x + ".h"  }.each do |h|
  CLOBBER.include(h)
end

for name in names
  file "#{name}.h" => "rbscript/#{name}.rb" do |t|
    rb = t.prerequisites[0]
    h = t.name
    sh "ruby #{rb} > #{h}"
  end
end 

task :gen_header => names.map { |x| x + ".h" }
