require "rake/clean"

require "thrusting"

include Thrusting
cc = make_default_compiler

cxx = cc.deepcopy
cxx.enable_debug_mode
cxx.make_gtest_task("gtest")

cxx = cc.deepcopy
cxx.make_gtest_task("gtest_no_debug")

cxx = cc.deepcopy
cxx.make_gtest_task("gtest_on_host", "host")

make_cat_task("gtest")
