require "rake/clean"

require "thrusting"

include Thrusting
cc = make_default_compiler
# cc.append("-D THRUSTING_PRETTY_PRINT_UNABLED")

cc.deepcopy.enable_debug_mode.make_gtest_task("gtest")
cc.deepcopy.make_gtest_task("gtest_no_debug")
cc.deepcopy.make_gtest_task("gtest_on_host", "host")
