require "rake/clean"

["def_compile", "make_compile_task", "compile_option"].each do |f|
  require "build/thrusting/#{f}"
end

["gtest"].each do |f|
  require "build/path/#{f}"
end

cc = THRUSTING_CXX

cc = with_mode(cc, "debug")
cc = use_gtest(cc)

make_compile_task(cc, "gtest")

dirname = "gtest"

task :regress_on_host => "#{dirname}:all_on_host" do |t|
  system "#{dirname}/all_on_host 1> host.regression"
end

task :regress_on_device => "#{dirname}:all_on_device" do |t|
  system "#{dirname}/all_on_device 1> device.regression"
end

task :regress_on_omp => "#{dirname}:all_on_omp" do |t|
  system "#{dirname}/all_on_omp 1> omp.regression"
end

task :regress_on_all => [:regress_on_host, :regress_on_device, :regress_on_omp]
