require "rake/clean"

["def_compile", "make_compile_task", "compile_option"].each do |f|
  require "build/thrusting/#{f}"
end

cc = THRUSTING_CXX

cc = with_mode(cc, "release")
p cc

make_compile_task(cc, "thrusting")
